title: Analyse de l’expression différentielle de genes à partir de données RNA-Seq (M2, année 2024-2025)
description: Apprendre à explorer des données de RNA-seq sur R
show_downloads: true
theme: jekyll-theme-hacker